import { useState, useRef, useCallback, useMemo } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Scissors, Upload, Download, Sparkles, Loader2, RotateCcw, Crown, Lock,
  User, Wand2, Star
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { generateContent } from "@/lib/ai";
import { useAuth } from "@/lib/auth";
import { useCredits } from "@/hooks/use-credits";
import { incrementUsage, getDailyUsage } from "@/lib/usage";
import { toast } from "sonner";
import { Link } from "react-router-dom";

/* ───── Constants ───── */
type HairLength = "short" | "medium" | "long";
type HairType = "fade" | "undercut" | "pompadour" | "curly" | "buzz" | "korean" | "messy" | "professional" | "wedding" | "corporate";
type BeardSync = "none" | "light" | "medium" | "premium";

const HAIR_LENGTHS: { value: HairLength; label: string; icon: string }[] = [
  { value: "short", label: "Short", icon: "✂️" },
  { value: "medium", label: "Medium", icon: "💇" },
  { value: "long", label: "Long", icon: "🧑‍🎤" },
];

const HAIR_TYPES: { value: HairType; label: string; icon: string }[] = [
  { value: "fade", label: "Fade Cut", icon: "🔲" },
  { value: "undercut", label: "Undercut", icon: "⚡" },
  { value: "pompadour", label: "Pompadour", icon: "🎩" },
  { value: "curly", label: "Curly", icon: "🌀" },
  { value: "buzz", label: "Buzz Cut", icon: "💈" },
  { value: "korean", label: "Korean Style", icon: "🇰🇷" },
  { value: "messy", label: "Messy", icon: "🌊" },
  { value: "professional", label: "Professional", icon: "👔" },
  { value: "wedding", label: "Wedding", icon: "💍" },
  { value: "corporate", label: "Corporate Formal", icon: "🏢" },
];

const BEARD_OPTIONS: { value: BeardSync; label: string; icon: string }[] = [
  { value: "none", label: "No Beard", icon: "🧑" },
  { value: "light", label: "Light Stubble", icon: "🧔‍♂️" },
  { value: "medium", label: "Medium Beard", icon: "🧔" },
  { value: "premium", label: "Premium Groomed", icon: "✨" },
];

const CELEBRITY_CHIPS = [
  { label: "Korean Hero", prompt: "Korean actor/idol style - clean, layered K-drama hairstyle with natural flow" },
  { label: "CEO Sharp", prompt: "CEO/executive sharp clean side-parted corporate hairstyle" },
  { label: "Groom Premium", prompt: "Wedding groom premium hairstyle - elegant, polished, formal" },
  { label: "Creator Style", prompt: "YouTuber/content creator trendy modern hairstyle" },
  { label: "Gamer Neon", prompt: "Gamer style edgy modern haircut with textured layers" },
];

const FREE_DAILY_LIMIT = 2;

/* ───── Watermark ───── */
function applyWatermark(imageSrc: string): Promise<string> {
  return new Promise((resolve) => {
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d")!;
      ctx.drawImage(img, 0, 0);
      const fontSize = Math.max(14, img.width * 0.03);
      ctx.font = `${fontSize}px sans-serif`;
      ctx.fillStyle = "rgba(255,255,255,0.55)";
      ctx.textAlign = "right";
      ctx.textBaseline = "bottom";
      ctx.fillText("Generated by Nova AI", img.width - 12, img.height - 10);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = () => resolve(imageSrc);
    img.src = imageSrc;
  });
}

/* ───── Main Component ───── */
const HairDesignAI = () => {
  const { user } = useAuth();
  const { plan, remaining, isAdmin } = useCredits();
  const isFree = plan === "free" && !isAdmin;

  const [uploadedImage, setUploadedImage] = useState<string | null>(null);
  const [resultImage, setResultImage] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processStep, setProcessStep] = useState("");

  const [hairLength, setHairLength] = useState<HairLength>("medium");
  const [hairType, setHairType] = useState<HairType>("professional");
  const [beardSync, setBeardSync] = useState<BeardSync>("none");
  const [customPrompt, setCustomPrompt] = useState("");
  const [aiSuggestion, setAiSuggestion] = useState(false);
  const [activeTab, setActiveTab] = useState("style");
  const [sliderPos, setSliderPos] = useState(50);
  const [isDragging, setIsDragging] = useState(false);

  const fileInputRef = useRef<HTMLInputElement>(null);
  const compareRef = useRef<HTMLDivElement>(null);

  const handleFileUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith("image/")) { toast.error("Please upload an image"); return; }
    if (file.size > 10 * 1024 * 1024) { toast.error("Max 10MB"); return; }
    const reader = new FileReader();
    reader.onload = () => { setUploadedImage(reader.result as string); setResultImage(null); };
    reader.readAsDataURL(file);
  }, []);

  const buildPrompt = useCallback((celebrityOverride?: string) => {
    const hairDesc = HAIR_TYPES.find(h => h.value === hairType)?.label || hairType;
    const lengthDesc = HAIR_LENGTHS.find(h => h.value === hairLength)?.label || hairLength;
    const beardDesc = BEARD_OPTIONS.find(b => b.value === beardSync)?.label || "none";

    const styleNote = celebrityOverride || customPrompt || `${lengthDesc} ${hairDesc} hairstyle`;
    const beardNote = beardSync === "none" ? "Clean shaven, no beard." : `Beard: ${beardDesc}, harmonized with hairstyle.`;
    const aiNote = aiSuggestion
      ? "AI AUTO: Analyze face shape and recommend the best hairstyle. Auto-adjust forehead balance, side fade precision, and hairline."
      : "";

    return `Transform this person's hairstyle into a premium professional result.

CRITICAL RULES:
- DO NOT change the person's face, identity, skin tone, or facial features AT ALL
- ONLY modify the hair and beard area
- The result must look like the EXACT SAME PERSON with a new hairstyle
- Maintain natural hairline and realistic hair texture
- Match lighting and shadows from original photo
- Clean edge blending at hairline
- Premium studio finish quality

HAIRSTYLE: ${styleNote}
HAIR LENGTH: ${lengthDesc}
${beardNote}
${aiNote}

QUALITY: Ultra-realistic, natural hair texture, professional lighting, no artifacts, no distortion.
OUTPUT: A clean professional photo with only the hairstyle changed.`;
  }, [hairType, hairLength, beardSync, customPrompt, aiSuggestion]);

  const handleGenerate = useCallback(async (celebrityOverride?: string) => {
    if (!uploadedImage || !user) { toast.error("Please upload a photo first"); return; }
    if (isFree) {
      const used = await getDailyUsage(user.id, "hair");
      if (used >= FREE_DAILY_LIMIT) { toast.error("Daily limit reached (2/day). Upgrade to Pro!"); return; }
    }

    setIsProcessing(true);
    setResultImage(null);
    try {
      setProcessStep("Analyzing face shape...");
      await new Promise(r => setTimeout(r, 400));
      setProcessStep("Designing hairstyle...");

      const prompt = buildPrompt(celebrityOverride);
      const result = await generateContent("hair-design", prompt, { image: uploadedImage });

      if (result.error) { toast.error(result.error); return; }
      if (result.images && result.images.length > 0) {
        let finalImage = result.images[0];
        if (isFree) finalImage = await applyWatermark(finalImage);
        setResultImage(finalImage);
        setSliderPos(50);
        await incrementUsage(user.id, "hair", isAdmin);
        toast.success("✨ Hair design complete!");
      } else {
        toast.error("Failed to generate. Try again.");
      }
    } catch {
      toast.error("Something went wrong.");
    } finally {
      setIsProcessing(false);
      setProcessStep("");
    }
  }, [uploadedImage, user, isFree, isAdmin, buildPrompt]);

  const handleDownload = useCallback(() => {
    if (!resultImage) return;
    const link = document.createElement("a");
    link.href = resultImage;
    link.download = `hair-design-${Date.now()}.png`;
    link.click();
    toast.success("Downloaded!");
  }, [resultImage]);

  const handleReset = useCallback(() => {
    setUploadedImage(null);
    setResultImage(null);
    setProcessStep("");
    setCustomPrompt("");
    if (fileInputRef.current) fileInputRef.current.value = "";
  }, []);

  const handleSliderDrag = useCallback((e: React.MouseEvent | React.TouchEvent) => {
    if (!compareRef.current) return;
    const rect = compareRef.current.getBoundingClientRect();
    const clientX = "touches" in e ? e.touches[0].clientX : e.clientX;
    const pos = Math.max(0, Math.min(100, ((clientX - rect.left) / rect.width) * 100));
    setSliderPos(pos);
  }, []);

  return (
    <div className="space-y-6 max-w-6xl mx-auto pb-10">
      <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5 }}>
        {/* Header */}
        <div className="flex items-center justify-between mb-6">
          <div className="flex items-center gap-3">
            <div className="w-12 h-12 rounded-2xl bg-gradient-to-br from-pink-500/20 to-purple-500/10 border border-pink-500/20 flex items-center justify-center">
              <Scissors className="w-6 h-6 text-pink-400" />
            </div>
            <div>
              <h1 className="text-2xl font-bold text-foreground">Hair Design AI</h1>
              <p className="text-sm text-muted-foreground">Transform your hairstyle with AI precision</p>
            </div>
          </div>
          {isFree && (
            <Link to="/dashboard/upgrade">
              <Button size="sm" variant="outline" className="gap-1.5 border-primary/30 text-primary hover:bg-primary/10">
                <Crown className="w-3.5 h-3.5" /> Upgrade
              </Button>
            </Link>
          )}
        </div>

        {isFree && (
          <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 flex items-center gap-3 mb-6">
            <Lock className="w-4 h-4 text-primary flex-shrink-0" />
            <p className="text-xs text-muted-foreground">
              <span className="text-foreground font-medium">Free plan:</span> 2 designs/day · Watermark ·{" "}
              <Link to="/dashboard/upgrade" className="text-primary hover:underline">Upgrade to Pro</Link>
            </p>
          </div>
        )}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Left: Controls */}
          <div className="space-y-4">
            {/* Upload */}
            <div className="rounded-xl border border-border/50 bg-card p-4 space-y-3">
              <Label className="text-sm font-medium">Upload Face Photo</Label>
              <input ref={fileInputRef} type="file" accept="image/*" onChange={handleFileUpload} className="hidden" />
              <Button variant="outline" className="w-full h-20 border-dashed border-2" onClick={() => fileInputRef.current?.click()}>
                <div className="flex flex-col items-center gap-1">
                  <Upload className="w-5 h-5 text-muted-foreground" />
                  <span className="text-xs text-muted-foreground">{uploadedImage ? "Change photo" : "Click to upload"}</span>
                </div>
              </Button>
            </div>

            {/* AI Suggestion Toggle */}
            <div className="rounded-xl border border-border/50 bg-card p-4">
              <div className="flex items-center justify-between">
                <div className="flex items-center gap-2">
                  <Sparkles className="w-4 h-4 text-amber-400" />
                  <Label className="text-sm font-medium">AI Auto Recommend</Label>
                </div>
                <Switch checked={aiSuggestion} onCheckedChange={setAiSuggestion} />
              </div>
              <p className="text-[10px] text-muted-foreground mt-1">Face-shape based auto recommendation</p>
            </div>

            <Tabs value={activeTab} onValueChange={setActiveTab}>
              <TabsList className="w-full grid grid-cols-2 h-9">
                <TabsTrigger value="style" className="text-xs">✂️ Style</TabsTrigger>
                <TabsTrigger value="celebrity" className="text-xs">⭐ Celebrity Match</TabsTrigger>
              </TabsList>

              <TabsContent value="style" className="space-y-4 mt-4">
                {/* Hair Length */}
                <div className="rounded-xl border border-border/50 bg-card p-4 space-y-2">
                  <Label className="text-xs text-muted-foreground">Hair Length</Label>
                  <Select value={hairLength} onValueChange={(v) => setHairLength(v as HairLength)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {HAIR_LENGTHS.map(h => (
                        <SelectItem key={h.value} value={h.value}>{h.icon} {h.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Hair Type */}
                <div className="rounded-xl border border-border/50 bg-card p-4 space-y-2">
                  <Label className="text-xs text-muted-foreground">Hair Type</Label>
                  <Select value={hairType} onValueChange={(v) => setHairType(v as HairType)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {HAIR_TYPES.map(h => (
                        <SelectItem key={h.value} value={h.value}>{h.icon} {h.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Beard Sync */}
                <div className="rounded-xl border border-border/50 bg-card p-4 space-y-2">
                  <Label className="text-xs text-muted-foreground">Beard Sync</Label>
                  <Select value={beardSync} onValueChange={(v) => setBeardSync(v as BeardSync)}>
                    <SelectTrigger><SelectValue /></SelectTrigger>
                    <SelectContent>
                      {BEARD_OPTIONS.map(b => (
                        <SelectItem key={b.value} value={b.value}>{b.icon} {b.label}</SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                </div>

                {/* Custom Prompt */}
                <div className="rounded-xl border border-border/50 bg-card p-4 space-y-2">
                  <Label className="text-xs text-muted-foreground">Custom Prompt (optional)</Label>
                  <Input
                    value={customPrompt}
                    onChange={(e) => setCustomPrompt(e.target.value)}
                    placeholder="e.g. korean look, wedding style, fade cut..."
                    className="text-sm h-9"
                  />
                </div>
              </TabsContent>

              <TabsContent value="celebrity" className="space-y-4 mt-4">
                <div className="rounded-xl border border-border/50 bg-card p-4 space-y-3">
                  <Label className="text-sm font-medium flex items-center gap-2">
                    <Star className="w-4 h-4 text-amber-400" /> Celebrity Hair Match
                  </Label>
                  <p className="text-[10px] text-muted-foreground">Pick a style — AI adapts it to your face shape</p>
                  <div className="flex flex-wrap gap-2">
                    {CELEBRITY_CHIPS.map(chip => (
                      <Button
                        key={chip.label}
                        variant="outline"
                        size="sm"
                        className="text-xs rounded-full"
                        disabled={isProcessing || !uploadedImage}
                        onClick={() => handleGenerate(chip.prompt)}
                      >
                        {chip.label}
                      </Button>
                    ))}
                  </div>
                </div>
              </TabsContent>
            </Tabs>

            {/* Action Buttons */}
            <div className="space-y-2">
              <Button className="w-full" size="lg" onClick={() => handleGenerate()} disabled={!uploadedImage || isProcessing}>
                {isProcessing ? (
                  <><Loader2 className="w-4 h-4 mr-2 animate-spin" />{processStep || "Processing..."}</>
                ) : (
                  <><Scissors className="w-4 h-4 mr-2" />Generate Hair Design</>
                )}
              </Button>
              {(uploadedImage || resultImage) && (
                <Button variant="outline" className="w-full" onClick={handleReset}>
                  <RotateCcw className="w-4 h-4 mr-2" /> Reset
                </Button>
              )}
            </div>
          </div>

          {/* Right: Preview */}
          <div className="lg:col-span-2 space-y-4">
            {/* Before/After Comparison */}
            {uploadedImage && resultImage ? (
              <div className="rounded-xl border border-border/50 bg-card overflow-hidden">
                <div className="px-4 py-2.5 border-b border-border/50 bg-muted/30 flex items-center justify-between">
                  <span className="text-xs font-medium text-muted-foreground">Before / After Comparison</span>
                  <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={handleDownload}>
                    <Download className="w-3 h-3 mr-1" /> Download
                  </Button>
                </div>
                <div
                  ref={compareRef}
                  className="relative aspect-[3/4] max-h-[500px] cursor-col-resize select-none overflow-hidden"
                  onMouseMove={(e) => isDragging && handleSliderDrag(e)}
                  onMouseDown={() => setIsDragging(true)}
                  onMouseUp={() => setIsDragging(false)}
                  onMouseLeave={() => setIsDragging(false)}
                  onTouchMove={handleSliderDrag}
                >
                  {/* After (full) */}
                  <img src={resultImage} alt="After" className="absolute inset-0 w-full h-full object-contain" />
                  {/* Before (clipped) */}
                  <div className="absolute inset-0 overflow-hidden" style={{ width: `${sliderPos}%` }}>
                    <img src={uploadedImage} alt="Before" className="absolute inset-0 w-full h-full object-contain" style={{ minWidth: `${100 / (sliderPos / 100)}%`, maxWidth: `${100 / (sliderPos / 100)}%` }} />
                  </div>
                  {/* Slider line */}
                  <div className="absolute top-0 bottom-0 w-0.5 bg-white/80 shadow-lg z-10" style={{ left: `${sliderPos}%` }}>
                    <div className="absolute top-1/2 -translate-y-1/2 -translate-x-1/2 w-8 h-8 rounded-full bg-white/90 shadow-lg flex items-center justify-center">
                      <span className="text-xs font-bold text-gray-700">⇔</span>
                    </div>
                  </div>
                  {/* Labels */}
                  <span className="absolute top-3 left-3 text-[10px] font-bold bg-black/50 text-white px-2 py-0.5 rounded z-10">BEFORE</span>
                  <span className="absolute top-3 right-3 text-[10px] font-bold bg-primary/80 text-white px-2 py-0.5 rounded z-10">AFTER</span>
                </div>
              </div>
            ) : (
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {/* Original */}
                <div className="rounded-xl border border-border/50 bg-card overflow-hidden">
                  <div className="px-4 py-2.5 border-b border-border/50 bg-muted/30">
                    <span className="text-xs font-medium text-muted-foreground">Original Photo</span>
                  </div>
                  <div className="aspect-[3/4] flex items-center justify-center bg-muted/10">
                    {uploadedImage ? (
                      <img src={uploadedImage} alt="Original" className="w-full h-full object-contain" />
                    ) : (
                      <div className="text-center p-6">
                        <User className="w-10 h-10 text-muted-foreground/30 mx-auto mb-2" />
                        <p className="text-sm text-muted-foreground/50">Upload a face photo to start</p>
                      </div>
                    )}
                  </div>
                </div>

                {/* Result */}
                <div className="rounded-xl border border-border/50 bg-card overflow-hidden">
                  <div className="px-4 py-2.5 border-b border-border/50 bg-muted/30">
                    <span className="text-xs font-medium text-muted-foreground">AI Result</span>
                  </div>
                  <div className="aspect-[3/4] flex items-center justify-center bg-muted/10">
                    <AnimatePresence mode="wait">
                      {isProcessing ? (
                        <motion.div key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center p-6">
                          <Loader2 className="w-10 h-10 text-primary mx-auto mb-3 animate-spin" />
                          <p className="text-sm text-muted-foreground">{processStep}</p>
                        </motion.div>
                      ) : (
                        <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center p-6">
                          <Scissors className="w-10 h-10 text-muted-foreground/30 mx-auto mb-2" />
                          <p className="text-sm text-muted-foreground/50">Result will appear here</p>
                        </motion.div>
                      )}
                    </AnimatePresence>
                  </div>
                </div>
              </div>
            )}

            {/* Credits info */}
            <div className="rounded-xl border border-border/50 bg-card p-3 text-center">
              <p className="text-xs text-muted-foreground">
                {isAdmin ? "∞ Admin access" : `${remaining} credits remaining today`}
              </p>
            </div>
          </div>
        </div>
      </motion.div>
    </div>
  );
};

export default HairDesignAI;
