import { useState, useRef, useCallback } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Camera, Upload, Download, Wand2, Shirt, Image as ImageIcon, Sparkles, Loader2, RotateCcw, Lock, Crown } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { generateContent } from "@/lib/ai";
import { useAuth } from "@/lib/auth";
import { useCredits } from "@/hooks/use-credits";
import { incrementUsage, getDailyUsage, saveToHistory } from "@/lib/usage";
import { toast } from "sonner";
import { Link } from "react-router-dom";

type DressStyle = "suit" | "shirt-tie" | "casual";
type Background = "white" | "light-gray" | "light-blue" | "red" | "office" | "studio";
type Enhancement = "natural" | "medium" | "high";
type ExportSize = "passport" | "square" | "hd" | "print-sheet";

const DRESS_OPTIONS: { value: DressStyle; label: string; icon: string }[] = [
  { value: "suit", label: "Formal Suit", icon: "🤵" },
  { value: "shirt-tie", label: "Shirt + Tie", icon: "👔" },
  { value: "casual", label: "Smart Casual", icon: "👕" },
];

const BG_OPTIONS: { value: Background; label: string; icon: string; proOnly?: boolean }[] = [
  { value: "white", label: "White (Passport)", icon: "⬜" },
  { value: "light-blue", label: "Light Blue", icon: "🔵" },
  { value: "red", label: "Red", icon: "🔴" },
  { value: "light-gray", label: "Light Gray", icon: "🔘" },
  { value: "office", label: "Office Blur", icon: "🏢", proOnly: true },
  { value: "studio", label: "Studio", icon: "📸", proOnly: true },
];

const ENHANCE_OPTIONS: { value: Enhancement; label: string }[] = [
  { value: "natural", label: "Natural" },
  { value: "medium", label: "Medium" },
  { value: "high", label: "High" },
];

const EXPORT_OPTIONS: { value: ExportSize; label: string; dimensions: string }[] = [
  { value: "passport", label: "Passport Size", dimensions: "413×531" },
  { value: "square", label: "Square (LinkedIn)", dimensions: "800×800" },
  { value: "hd", label: "HD Image", dimensions: "1200×1500" },
  { value: "print-sheet", label: "Print Sheet (6x)", dimensions: "1800×1200" },
];

const FREE_DAILY_LIMIT = 2;

function applyWatermark(imageSrc: string): Promise<string> {
  return new Promise((resolve) => {
    const img = new window.Image();
    img.crossOrigin = "anonymous";
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = img.width;
      canvas.height = img.height;
      const ctx = canvas.getContext("2d")!;
      ctx.drawImage(img, 0, 0);
      const fontSize = Math.max(14, img.width * 0.03);
      ctx.font = `${fontSize}px sans-serif`;
      ctx.fillStyle = "rgba(255,255,255,0.55)";
      ctx.textAlign = "right";
      ctx.textBaseline = "bottom";
      ctx.fillText("Generated by Nova AI", img.width - 12, img.height - 10);
      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = () => resolve(imageSrc);
    img.src = imageSrc;
  });
}

const PhotoMaker = () => {
  const { user } = useAuth();
  const { plan, isAdmin } = useCredits();
  const isFree = plan === "free" && !isAdmin;

  const [uploadedImage, setUploadedImage] = useState<string | null>(null);
  const [resultImage, setResultImage] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [processStep, setProcessStep] = useState("");

  const [dressStyle, setDressStyle] = useState<DressStyle>("suit");
  const [background, setBackground] = useState<Background>("white");
  const [enhancement, setEnhancement] = useState<Enhancement>(isFree ? "natural" : "medium");
  const [exportSize, setExportSize] = useState<ExportSize>("square");
  const [aiAutoMode, setAiAutoMode] = useState(true);
  const [autoRemoveBg, setAutoRemoveBg] = useState(true);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const handleFileUpload = useCallback((e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;
    if (!file.type.startsWith("image/")) { toast.error("Please upload an image file"); return; }
    if (file.size > 10 * 1024 * 1024) { toast.error("Image must be under 10MB"); return; }
    const reader = new FileReader();
    reader.onload = () => { setUploadedImage(reader.result as string); setResultImage(null); };
    reader.readAsDataURL(file);
  }, []);

  const handleGenerate = useCallback(async () => {
    if (!uploadedImage || !user) { toast.error("Please upload a photo first"); return; }
    if (isProcessing) return;

    if (isFree) {
      const used = await getDailyUsage(user.id, "photo");
      if (used >= FREE_DAILY_LIMIT) {
        toast.error("Daily limit reached (2/day). Upgrade to Pro for unlimited!");
        return;
      }
    }

    const effectiveBg = (isFree && (background === "office" || background === "studio")) ? "white" : background;

    setIsProcessing(true);
    setResultImage(null);

    const bgDesc: Record<Background, string> = {
      white: "pure white clean passport-style background",
      "light-gray": "soft light gray gradient studio background",
      "light-blue": "official light blue passport background (standard government blue)",
      red: "solid red background for official ID photos",
      office: "professional office environment with soft bokeh blur background",
      studio: "professional photography studio with soft lighting background",
    };
    const dressDesc: Record<DressStyle, string> = {
      suit: "formal black or navy business suit with white shirt",
      "shirt-tie": "professional dress shirt with a matching tie",
      casual: "smart casual polo or button-up shirt",
    };
    const enhanceDesc: Record<Enhancement, string> = {
      natural: "subtle natural enhancement, minimal retouching, keep original look",
      medium: "moderate enhancement, smooth skin, good lighting balance, natural colors",
      high: "high enhancement, perfect skin, studio-quality lighting, sharp details",
    };

    const autoNote = aiAutoMode
      ? "AI AUTO MODE: Automatically choose the best combination of background, outfit and lighting for a professional look."
      : "Follow the specific user choices below exactly.";

    const removeBgNote = autoRemoveBg
      ? "IMPORTANT: First remove the existing background completely, then apply the new background."
      : "";

    const qualityNote = isFree
      ? "Output in standard quality (720p equivalent)."
      : "Output in maximum HD quality with sharp details.";

    const prompt = `Transform this person's photo into a PROFESSIONAL OFFICIAL PHOTO suitable for CV, LinkedIn, passport, or job applications.

${autoNote}
${removeBgNote}

CRITICAL RULES:
- DO NOT change the person's face identity AT ALL
- DO NOT over-beautify or make the face look artificial
- Keep the person's natural facial features, skin tone, and identity
- The result must look like the SAME PERSON

PASSPORT CROP RULES (VERY IMPORTANT):
- Face must be perfectly centered in the frame
- Maintain safe margin above forehead (15-20% of image height)
- Chin spacing balanced with equal space below
- Both ears should be visible if possible
- Shoulders aligned and evenly cropped
- Follow standard passport photo ratio (35mm × 45mm proportions)
- Head should occupy 70-80% of the frame height

BACKGROUND: ${bgDesc[effectiveBg]}
CLOTHING: Replace current clothing with ${dressDesc[dressStyle]}. Match lighting and shadows naturally.
ENHANCEMENT: ${enhanceDesc[isFree ? "natural" : enhancement]}
${qualityNote}

ADDITIONAL: Fix lighting, clean hair, remove noise, natural skin tones, professional lighting.
OUTPUT: A clean, professional headshot photo ready for official use with perfect passport-standard cropping.`;

    let lastError = "";

    for (let attempt = 0; attempt < 2; attempt++) {
      try {
        if (attempt === 0) {
          setProcessStep("Analyzing photo...");
          await new Promise(r => setTimeout(r, 400));
          setProcessStep("Enhancing professionally...");
        } else {
          setProcessStep("Retrying generation...");
          toast.info("Taking longer than usual. Retrying...");
        }

        const result = await generateContent("photo-enhance", prompt, { image: uploadedImage });

        if (result.error) {
          lastError = result.error;
          if (attempt === 0) continue;
          break;
        }

        if (result.images && result.images.length > 0) {
          let finalImage = result.images[0];
          if (isFree) finalImage = await applyWatermark(finalImage);
          setResultImage(finalImage);
          await incrementUsage(user.id, "photo", isAdmin);
          await saveToHistory(user.id, "photo", `Photo: ${dressStyle} on ${effectiveBg}`, prompt, finalImage.slice(0, 200));
          toast.success("✨ Professional photo generated!");
          setIsProcessing(false);
          setProcessStep("");
          return;
        } else {
          lastError = "No image returned";
          if (attempt === 0) continue;
        }
      } catch (e) {
        lastError = e instanceof Error ? e.message : "Something went wrong";
        if (attempt === 0) continue;
      }
    }

    toast.error(lastError || "Failed to generate. Please try again.");
    setIsProcessing(false);
    setProcessStep("");
  }, [uploadedImage, user, isFree, isAdmin, isProcessing, background, dressStyle, enhancement, aiAutoMode, autoRemoveBg]);

  const handleDownload = useCallback(() => {
    if (!resultImage) return;
    const link = document.createElement("a");
    link.href = resultImage;
    link.download = `professional-photo-${exportSize}.png`;
    link.click();
    toast.success("Photo downloaded!");
  }, [resultImage, exportSize]);

  const handleReset = useCallback(() => {
    setUploadedImage(null);
    setResultImage(null);
    setProcessStep("");
    if (fileInputRef.current) fileInputRef.current.value = "";
  }, []);

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="p-2.5 rounded-xl bg-primary/10 border border-primary/20">
            <Camera className="w-6 h-6 text-primary" />
          </div>
          <div>
            <h1 className="text-2xl font-bold text-foreground">AI Professional Photo Maker</h1>
            <p className="text-sm text-muted-foreground">Transform any photo into a professional headshot</p>
          </div>
        </div>
        {isFree && (
          <Link to="/dashboard/upgrade">
            <Button size="sm" variant="outline" className="gap-1.5 border-primary/30 text-primary hover:bg-primary/10">
              <Crown className="w-3.5 h-3.5" /> Upgrade for HD
            </Button>
          </Link>
        )}
      </div>

      {isFree && (
        <div className="rounded-xl border border-primary/20 bg-primary/5 p-3 flex items-center gap-3">
          <Lock className="w-4 h-4 text-primary flex-shrink-0" />
          <p className="text-xs text-muted-foreground">
            <span className="text-foreground font-medium">Free plan:</span> 2 photos/day · Standard quality · Watermark ·{" "}
            <Link to="/dashboard/upgrade" className="text-primary hover:underline">Upgrade to Pro</Link> for HD, no watermark & unlimited
          </p>
        </div>
      )}

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        {/* Left: Controls */}
        <div className="space-y-4">
          {/* Upload */}
          <div className="rounded-xl border border-border/50 bg-card p-4 space-y-3">
            <Label className="text-sm font-medium">Upload Photo</Label>
            <input ref={fileInputRef} type="file" accept="image/*" onChange={handleFileUpload} className="hidden" />
            <Button variant="outline" className="w-full h-20 border-dashed border-2" onClick={() => fileInputRef.current?.click()}>
              <div className="flex flex-col items-center gap-1">
                <Upload className="w-5 h-5 text-muted-foreground" />
                <span className="text-xs text-muted-foreground">{uploadedImage ? "Change photo" : "Click to upload"}</span>
              </div>
            </Button>
          </div>

          {/* Toggles */}
          <div className="rounded-xl border border-border/50 bg-card p-4 space-y-3">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <Sparkles className="w-4 h-4 text-primary" />
                <Label className="text-sm font-medium">AI Auto Mode</Label>
              </div>
              <Switch checked={aiAutoMode} onCheckedChange={setAiAutoMode} />
            </div>
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <ImageIcon className="w-4 h-4 text-primary" />
                <Label className="text-sm font-medium">Auto Remove BG</Label>
              </div>
              <Switch checked={autoRemoveBg} onCheckedChange={setAutoRemoveBg} />
            </div>
          </div>

          {/* Dress Style */}
          <div className="rounded-xl border border-border/50 bg-card p-4 space-y-2">
            <div className="flex items-center gap-2">
              <Shirt className="w-4 h-4 text-muted-foreground" />
              <Label className="text-sm font-medium">Dress Style</Label>
            </div>
            <Select value={dressStyle} onValueChange={(v) => setDressStyle(v as DressStyle)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {DRESS_OPTIONS.map((o) => (
                  <SelectItem key={o.value} value={o.value}>{o.icon} {o.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Background */}
          <div className="rounded-xl border border-border/50 bg-card p-4 space-y-2">
            <div className="flex items-center gap-2">
              <ImageIcon className="w-4 h-4 text-muted-foreground" />
              <Label className="text-sm font-medium">Background</Label>
            </div>
            <Select value={background} onValueChange={(v) => setBackground(v as Background)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {BG_OPTIONS.map((o) => (
                  <SelectItem key={o.value} value={o.value} disabled={isFree && o.proOnly}>
                    {o.icon} {o.label} {isFree && o.proOnly ? "🔒 Pro" : ""}
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Enhancement Level */}
          <div className="rounded-xl border border-border/50 bg-card p-4 space-y-2">
            <div className="flex items-center gap-2">
              <Wand2 className="w-4 h-4 text-muted-foreground" />
              <Label className="text-sm font-medium">Enhancement {isFree && <span className="text-primary text-[10px]">(Pro: Medium/High)</span>}</Label>
            </div>
            <Select value={isFree ? "natural" : enhancement} onValueChange={(v) => !isFree && setEnhancement(v as Enhancement)} disabled={isFree}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {ENHANCE_OPTIONS.map((o) => (
                  <SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Export Size */}
          <div className="rounded-xl border border-border/50 bg-card p-4 space-y-2">
            <div className="flex items-center gap-2">
              <Download className="w-4 h-4 text-muted-foreground" />
              <Label className="text-sm font-medium">Export Size</Label>
            </div>
            <Select value={exportSize} onValueChange={(v) => setExportSize(v as ExportSize)}>
              <SelectTrigger><SelectValue /></SelectTrigger>
              <SelectContent>
                {EXPORT_OPTIONS.map((o) => (
                  <SelectItem key={o.value} value={o.value}>{o.label} ({o.dimensions})</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>

          {/* Action buttons */}
          <div className="space-y-2">
            <Button className="w-full" size="lg" onClick={handleGenerate} disabled={!uploadedImage || isProcessing}>
              {isProcessing ? (
                <><Loader2 className="w-4 h-4 mr-2 animate-spin" />{processStep || "Processing..."}</>
              ) : (
                <><Wand2 className="w-4 h-4 mr-2" />Generate Professional Photo</>
              )}
            </Button>
            {(uploadedImage || resultImage) && (
              <Button variant="outline" className="w-full" onClick={handleReset}>
                <RotateCcw className="w-4 h-4 mr-2" /> Reset
              </Button>
            )}
          </div>
        </div>

        {/* Right: Preview */}
        <div className="lg:col-span-2 space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            {/* Original */}
            <div className="rounded-xl border border-border/50 bg-card overflow-hidden">
              <div className="px-4 py-2.5 border-b border-border/50 bg-muted/30">
                <span className="text-xs font-medium text-muted-foreground">Original Photo</span>
              </div>
              <div className="aspect-[3/4] flex items-center justify-center bg-muted/10">
                {uploadedImage ? (
                  <img src={uploadedImage} alt="Original" className="w-full h-full object-contain" />
                ) : (
                  <div className="text-center p-6">
                    <Camera className="w-10 h-10 text-muted-foreground/30 mx-auto mb-2" />
                    <p className="text-sm text-muted-foreground/50">Upload a photo to start</p>
                  </div>
                )}
              </div>
            </div>

            {/* Result */}
            <div className="rounded-xl border border-border/50 bg-card overflow-hidden">
              <div className="px-4 py-2.5 border-b border-border/50 bg-muted/30 flex items-center justify-between">
                <span className="text-xs font-medium text-muted-foreground">Professional Result</span>
                {resultImage && (
                  <Button size="sm" variant="ghost" className="h-7 text-xs" onClick={handleDownload}>
                    <Download className="w-3 h-3 mr-1" /> Download
                  </Button>
                )}
              </div>
              <div className="aspect-[3/4] flex items-center justify-center bg-muted/10 relative">
                <AnimatePresence mode="wait">
                  {isProcessing ? (
                    <motion.div key="loading" initial={{ opacity: 0 }} animate={{ opacity: 1 }} exit={{ opacity: 0 }} className="text-center p-6">
                      <Loader2 className="w-10 h-10 text-primary mx-auto mb-3 animate-spin" />
                      <p className="text-sm text-muted-foreground">{processStep}</p>
                    </motion.div>
                  ) : resultImage ? (
                    <motion.img key="result" initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} src={resultImage} alt="Professional result" className="w-full h-full object-contain" />
                  ) : (
                    <motion.div key="empty" initial={{ opacity: 0 }} animate={{ opacity: 1 }} className="text-center p-6">
                      <Sparkles className="w-10 h-10 text-muted-foreground/30 mx-auto mb-2" />
                      <p className="text-sm text-muted-foreground/50">Result will appear here</p>
                    </motion.div>
                  )}
                </AnimatePresence>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
};

export default PhotoMaker;
