// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mbdbahrkgnfsadfjujpt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1iZGJhaHJrZ25mc2FkZmp1anB0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzM1ODA0MzIsImV4cCI6MjA4OTE1NjQzMn0.78H3hpwk9VEu57iBV_zVWVruIHBON1BHlqlNCFYpvQI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});